Simple objects no longer iterate over all sub populations
EC-KitY/EC-KitY pull request #105
Opened 2024-05-19 18:31 UTC by itaitzruia4

Handles #65 
(under the assumption that Simple objects assume 1 sub population)

2024-05-21 19:51 UTC, itaitzruia4 commented
should be merged after #104

2024-05-29 18:32 UTC, itaitzruia4 commented
Closing and reopening to run checks

2024-06-19 18:07 UTC, achiyae requested changes

2024-06-19 18:07 UTC, achiyae commented on eckity/evaluators/simple_population_evaluator.py
> +        sub_population = population.sub_populations[0]
add assert before that there is only one sub population

2024-06-29 17:15 UTC, itaitzruia4 commented on eckity/evaluators/simple_population_evaluator.py
> +        sub_population = population.sub_populations[0]
done, also added a check in `SimpleBreeder`

2024-07-10 19:24 UTC, merged