Selection
EC-KitY/EC-KitY pull request #116
Opened 2024-06-18 17:24 UTC by itaitzruia4

- Implemented Fitness Proportionate selection (AKA Roulette Wheel selection)
- Added arity validation in Algorithm (to prevent runtime errors in cases of 10 population size and 3 parents crossover for instance)
- Added `replace` parameter in Tournament selection, that allows the choice of individuals for the tournament to be either with or without replacement (by default, replace=True for backwards compatibility)

2024-06-19 18:25 UTC, achiyae requested changes

2024-06-19 18:25 UTC, achiyae commented on eckity/algorithms/algorithm.py
> +                        f"Operator {oper} arity must be "
Move to breeder

2024-06-19 18:25 UTC, achiyae commented on eckity/algorithms/tests/test_algorithm.py
should be moved to breeder as well

2024-06-19 18:25 UTC, achiyae commented on eckity/genetic_operators/selections/fp_selection.py
> +            fitness_scores = -fitness_scores
need to check that there are no minus fitness values. see https://github.com/GMUEClab/ecj/blob/10a5debd0edbb47fb0fba02da79c8086db9e1dc9/ecj/src/main/java/ec/select/FitProportionateSelection.java#L71

2024-06-28 13:30 UTC, itaitzruia4 commented
@achiyae all changes were done, version-detector still doesn't work properly
I think we can just remove it and manually check version changes in CR

2024-07-10 19:52 UTC, merged