use logging instead of simple 'print's
EC-KitY/EC-KitY pull request #66
Opened 2023-06-21 11:18 UTC by ZvikaZ

Solves issue https://github.com/EC-KitY/EC-KitY/issues/33 .
And maybe also makes https://github.com/EC-KitY/EC-KitY/issues/46 redundant.

2023-06-21 17:36 UTC, achiyae requested changes
Thanks for the hard work!

2023-06-21 17:36 UTC, achiyae commented on eckity/algorithms/algorithm.py
> +		logger.debug('random seed =', self.random_seed)
I think that it sould be info rather than debug. It is informative...

2023-06-21 17:36 UTC, achiyae commented on eckity/genetic_encodings/ga/vector_individual.py
> +        logger.info(self.vector)
Should be debug

2023-06-21 17:36 UTC, achiyae commented on eckity/genetic_encodings/gp/tree/tree_individual.py
> +            logger.info(self.tree[end_i], list)
Debug

2023-06-21 17:36 UTC, achiyae commented on eckity/genetic_encodings/gp/tree/tree_individual.py
> +                self._str_rec(prefix + "   ", pos, result, use_python_syntax)
This str_rec function changes should be moved to another PR

2023-06-21 17:36 UTC, achiyae commented on eckity/statistics/best_average_worst_statistics.py
> +import logging
Statistics shouldn't use logger... 
Stream is a better option

2023-06-21 17:36 UTC, achiyae commented on eckity/statistics/best_avg_worst_size_tree_statistics.py
> +import logging
Statistics shouldn't use logger...
Stream is a better option

2023-06-21 17:36 UTC, achiyae commented on eckity/statistics/minimal_print_statistics.py
> +import logging
Statistics shouldn't use logger...
Stream is a better option

2023-06-21 17:36 UTC, achiyae commented on eckity/statistics/statistics.py
> -from sys import stdout
Statistics shouldn't use logger...
Stream is a better option

2023-06-22 07:26 UTC, ZvikaZ commented on eckity/algorithms/algorithm.py
> +		logger.debug('random seed =', self.random_seed)
I was under the impression of https://github.com/EC-KitY/EC-KitY/issues/46 that made me think that it's desired to not always print this message.
And of the `'debug'` string in the original `print`.

Anyway, I changed it as you requested.

2023-06-22 07:26 UTC, ZvikaZ commented on eckity/genetic_encodings/ga/vector_individual.py
> +        logger.info(self.vector)
Done

2023-06-22 07:26 UTC, ZvikaZ commented on eckity/genetic_encodings/gp/tree/tree_individual.py
> +            logger.info(self.tree[end_i], list)
Done

2023-06-22 07:28 UTC, ZvikaZ commented on eckity/genetic_encodings/gp/tree/tree_individual.py
> +                self._str_rec(prefix + "   ", pos, result, use_python_syntax)
I can do it if you wish. However, in that case the `logger` behaviour will be different than the `print` behaviour. I wrote this code in order to not introduce changes in the resulting printing.

What do you prefer?

2023-06-22 07:31 UTC, ZvikaZ commented on eckity/statistics/best_average_worst_statistics.py
> +import logging
I don't understand why?
Logger is the standard Python way to handle all simple. or sophisticated, printing to screen/writing to file combinations.
Using logger we can have easy control what goes where, with a familiar API.

As far as I understand, everything that can be done with Stream can be done with Logger, but not the opposite.

2023-06-27 09:35 UTC, achiyae requested changes

2023-06-27 09:35 UTC, achiyae commented on eckity/genetic_encodings/gp/tree/tree_individual.py
> +                self._str_rec(prefix + "   ", pos, result, use_python_syntax)
Agreed, closes #34

2023-06-27 09:35 UTC, achiyae commented on eckity/genetic_encodings/gp/tree/tree_individual.py
> +    def __str__(self, use_python_syntax=False):
Remove the "usePythonSyntax" variable and make it default

2023-06-27 09:35 UTC, achiyae commented on eckity/genetic_encodings/gp/tree/tree_individual.py
> +    def _str_rec(self, prefix, pos, result, use_python_syntax):
Add unittest. What happens if node itself is multiline

2023-06-27 09:35 UTC, achiyae commented on eckity/statistics/best_average_worst_statistics.py
> +import logging
Agreed - used logger

2023-06-27 09:35 UTC, achiyae commented
Closes #34

2024-05-08 12:57 UTC, merged